CREATE TABLE [dbo].[CUSTOMER_TRANSACTIONS]
(
	[ID] INT NOT NULL PRIMARY KEY, 
    [ACCOUNT_FROM] VARCHAR(50) NOT NULL, 
    [ACCOUNT_TO] VARCHAR(50) NOT NULL, 
    [CUSTOMER_ID] INT NOT NULL, 
    [ACCOUNT_ID] INT NOT NULL,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_INFO(ID),
	FOREIGN KEY (ACCOUNT_ID) REFERENCES CUSTOMER_ACCOUNTS(ID)
)
