CREATE TABLE [dbo].[CUSTOMER_TRANSACTIONS]
(
	[ID] INT NOT NULL PRIMARY KEY, 
    [CUSTOMER_ID_FROM] INT NOT NULL, 
    [ACCOUNT_ID_FROM] INT NOT NULL,
	[DATE_SUBMITED] DATETIME NOT NULL, 
    [AMOUNT] MONEY NOT NULL, 
    [CUSTOMER_ID_TO] INT NOT NULL, 
    [ACCOUNT_ID_TO] INT NOT NULL, 
    FOREIGN KEY ([CUSTOMER_ID_FROM]) REFERENCES CUSTOMER_INFO(ID),
	FOREIGN KEY ([ACCOUNT_ID_FROM]) REFERENCES CUSTOMER_ACCOUNTS(ID),
	FOREIGN KEY ([CUSTOMER_ID_TO]) REFERENCES CUSTOMER_INFO(ID),
	FOREIGN KEY ([ACCOUNT_ID_TO]) REFERENCES CUSTOMER_ACCOUNTS(ID)
)
