CREATE TABLE [dbo].[CUSTOMER_ACCOUNTS]
(
	[ID] INT NOT NULL PRIMARY KEY, 
    [CUSTOMER_ID] INT NOT NULL, 
    [BALANCE] MONEY NOT NULL, 
    [ACCOUNT_NUMBER] VARCHAR(50) NOT NULL, 
    [DATE_CREATED] DATETIME NOT NULL, 
    [ACCOUNT_TYPE] VARCHAR(10) NOT NULL, 
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_INFO(ID)
)
